import { Platform, StyleSheet } from "react-native";

export const serifFont = Platform.select({
  ios: "Georgia",
  android: "serif",
  default: "serif",
});

/** Dropdown picker used for room type, roommate gender and zone. */
export const dropdownStyles = StyleSheet.create({
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    width: "100%",
    maxHeight: "80%",
  },
  modalContent: {
    backgroundColor: "#FFFDFC",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: Platform.OS === "ios" ? 36 : 24,
    maxHeight: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE8E1",
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#463826",
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F4ECE4",
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: {
    fontSize: 14,
    color: "#7F232D",
    fontWeight: "600",
  },
  searchContainer: {
    marginBottom: 12,
  },
  searchInput: {
    backgroundColor: "#FAF6F0",
    borderRadius: 12,
    paddingHorizontal: 14,
    height: 44,
    borderWidth: 1,
    borderColor: "#EADCD3",
    fontSize: 14,
    color: "#463826",
  },
  optionsList: {
    maxHeight: 340,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingVertical: 8,
  },
  ageChip: {
    width: 58,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#FAF6F0",
    borderWidth: 1,
    borderColor: "#EADCD3",
    alignItems: "center",
    justifyContent: "center",
  },
  chipSelected: {
    backgroundColor: "#C64338",
    borderColor: "#C64338",
  },
  ageChipText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#463826",
  },
  chipTextSelected: {
    color: "#FFFFFF",
  },
  listContainer: {
    gap: 6,
    paddingVertical: 4,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: "#FAF6F0",
    borderWidth: 1,
    borderColor: "transparent",
  },
  itemSelected: {
    backgroundColor: "#FFF0BB",
    borderColor: "#FFD477",
  },
  itemText: {
    fontSize: 15,
    color: "#463826",
    fontWeight: "500",
  },
  itemTextSelected: {
    fontWeight: "700",
    color: "#7F232D",
  },
  checkMark: {
    fontSize: 16,
    color: "#C64338",
    fontWeight: "bold",
  },
  customItem: {
    backgroundColor: "#FEEAE6",
    borderColor: "#F0CDBF",
  },
  customItemText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#C64338",
  },
});

/** The two-step profile setup form. */
export const housingStyles = StyleSheet.create({
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#FAF6F0",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  backChevron: {
    fontSize: 18,
    color: "#463826",
    fontWeight: "bold",
  },
  headerTitle: {
    fontFamily: serifFont,
    fontSize: 22,
    fontWeight: "bold",
    color: "#463826",
  },
  sectionCard: {
    backgroundColor: "#FAF6F0",
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  sectionTitle: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 12,
  },
  yearGrid: {
    flexDirection: "row",
    gap: 8,
  },
  yearChip: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EADCD3",
    alignItems: "center",
    justifyContent: "center",
  },
  yearChipSelected: {
    backgroundColor: "#C64338",
    borderColor: "#C64338",
  },
  yearText: {
    fontFamily: serifFont,
    fontSize: 14,
    fontWeight: "600",
    color: "#463826",
  },
  yearTextSelected: {
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  zoneGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  zoneCard: {
    width: "48%",
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#EADCD3",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    position: "relative",
  },
  zoneCardSelected: {
    backgroundColor: "#FFF0BB",
    borderColor: "#FFD477",
  },
  zoneIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  zoneLabel: {
    fontFamily: serifFont,
    fontSize: 13,
    fontWeight: "600",
    color: "#463826",
    flex: 1,
  },
  zoneLabelSelected: {
    fontWeight: "bold",
    color: "#7F232D",
  },
  zoneBadge: {
    position: "absolute",
    top: 6,
    right: 8,
    fontSize: 13,
    color: "#C64338",
    fontWeight: "bold",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  budgetValueText: {
    fontFamily: serifFont,
    fontSize: 14,
    fontWeight: "bold",
    color: "#C64338",
  },
  budgetGrid: {
    gap: 8,
  },
  budgetChip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  budgetChipSelected: {
    backgroundColor: "#FFF0BB",
    borderColor: "#FFD477",
  },
  budgetChipLabel: {
    fontFamily: serifFont,
    fontSize: 14,
    fontWeight: "600",
    color: "#463826",
  },
  budgetChipLabelSelected: {
    fontWeight: "bold",
    color: "#7F232D",
  },
  budgetChipSub: {
    fontFamily: serifFont,
    fontSize: 12,
    color: "#8D7C75",
  },
  budgetChipSubSelected: {
    color: "#C64338",
    fontWeight: "bold",
  },
});
