import { Platform, StyleSheet } from "react-native";

export const serifFont = Platform.select({
  ios: "Georgia",
  android: "serif",
  default: "serif",
});

/** Page chrome shared by the four profile-area screens. */
export const profileStyle = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#FEFCFA",
  },
  page: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  pageTitle: {
    fontFamily: serifFont,
    fontSize: 24,
    fontWeight: "bold",
    color: "#463826",
  },
  settingsButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FAF6F0",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  settingsIcon: {
    fontSize: 18,
  },
  identityCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#EADCD3",
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  avatarWrap: {
    position: "relative",
    marginRight: 16,
  },
  profileAvatar: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#F0CDBF",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarInitial: {
    fontFamily: serifFont,
    fontSize: 28,
    fontWeight: "bold",
    color: "#7F232D",
  },
  editBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#C64338",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  editBadgeText: {
    fontSize: 11,
    color: "#FFFFFF",
  },
  identityCopy: {
    flex: 1,
  },
  name: {
    fontFamily: serifFont,
    fontSize: 20,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 2,
  },
  meta: {
    fontFamily: serifFont,
    fontSize: 13,
    color: "#8D7C75",
    marginBottom: 8,
  },
  verificationPill: {
    alignSelf: "flex-start",
    backgroundColor: "#E6F4EA",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CEEAD6",
  },
  pendingPill: {
    backgroundColor: "#FFF8E1",
    borderColor: "#FFE082",
  },
  verificationText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#137333",
  },
  pendingText: {
    color: "#B06000",
  },
  sectionCard: {
    backgroundColor: "#FAF6F0",
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  cardTitle: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#463826",
  },
  strengthPercent: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#C64338",
  },
  strengthTrack: {
    height: 8,
    backgroundColor: "#EADCD3",
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 10,
  },
  strengthFill: {
    height: "100%",
    backgroundColor: "#C64338",
    borderRadius: 4,
  },
  description: {
    fontFamily: serifFont,
    fontSize: 13,
    color: "#74675E",
    lineHeight: 18,
  },
  shortcutRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  shortcutIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#FAF6F0",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  shortcutTitle: {
    fontFamily: serifFont,
    fontSize: 14,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 2,
  },
  shortcutSub: {
    fontFamily: serifFont,
    fontSize: 12,
    color: "#8D7C75",
  },
  chevron: {
    fontSize: 18,
    color: "#8D7C75",
    fontWeight: "bold",
    marginLeft: 8,
  },
  pressed: {
    opacity: 0.8,
  },
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    marginTop: 12,
    fontFamily: serifFont,
    color: "#8D7C75",
  },
  retryButton: {
    marginTop: 16,
    backgroundColor: "#C64338",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
  },
  retryText: {
    color: "#FFFFFF",
    fontWeight: "bold",
  },
});
