import { StyleSheet } from "react-native";
import { C } from "./colors";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.bg,
  },
  page: {
    flexGrow: 1,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingTop: 18,
    gap: 14,
  },
  splash: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.wine,
  },
  logo: {
    width: 66,
    height: 66,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,.13)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,.3)",
  },
  logoText: { fontSize: 38, color: C.amber },
  logoImage: {
    width: 116,
    height: 116,
  },
  brand: {
    fontFamily: "NotoSansThai_800ExtraBold",
    fontSize: 28,
    lineHeight: 40,
    textAlign: "center",
    color: "#fff",
    marginTop: 24,
  },
  splashTag: { color: "#F5C9CA", marginTop: 12 },
  university: {
    position: "absolute",
    bottom: 34,
    color: "#E8AAA8",
    fontSize: 9,
    letterSpacing: 2,
  },
  header: {
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontFamily: "NotoSansThai_800ExtraBold",
    fontSize: 20,
    color: C.ink,
  },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  back: { fontSize: 28, color: C.wine, lineHeight: 30 },
  pill: {
    borderWidth: 1,
    borderColor: C.orange,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  pillText: {
    fontSize: 11,
    color: C.orange,
    fontFamily: "NotoSansThai_700Bold",
  },
  title: { fontFamily: "NotoSansThai_700Bold", fontSize: 16, color: C.ink },
  bigTitle: {
    fontFamily: "NotoSansThai_800ExtraBold",
    fontSize: 24,
    lineHeight: 32,
    textAlign: "center",
    color: C.ink,
  },
  bigTitleLeft: {
    fontFamily: "NotoSansThai_800ExtraBold",
    fontSize: 23,
    color: C.ink,
    marginTop: 8,
  },
  muted: {
    color: C.muted,
    fontFamily: "NotoSansThai_400Regular",
    fontSize: 12,
  },
  centerMuted: {
    color: C.muted,
    fontFamily: "NotoSansThai_400Regular",
    fontSize: 13,
    lineHeight: 21,
    textAlign: "center",
  },
  label: {
    fontFamily: "NotoSansThai_700Bold",
    fontSize: 11,
    letterSpacing: 0.8,
    color: C.muted,
    marginBottom: 7,
  },
  link: { color: C.orange, fontFamily: "NotoSansThai_700Bold", fontSize: 12 },
  note: {
    fontFamily: "NotoSansThai_400Regular",
    fontSize: 11,
    lineHeight: 18,
    color: "#826B6D",
  },
  tinyOrange: {
    color: C.orange,
    fontFamily: "NotoSansThai_700Bold",
    fontSize: 11,
  },
  error: {
    color: "#B42336",
    backgroundColor: "#FFF0F3",
    padding: 10,
    borderRadius: 10,
    fontFamily: "NotoSansThai_600SemiBold",
  },
  button: {
    height: 52,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 4,
  },
  buttonText: {
    fontFamily: "NotoSansThai_800ExtraBold",
    fontSize: 14,
    color: "#fff",
  },
  input: {
    height: 54,
    borderWidth: 1.5,
    borderColor: C.line,
    borderRadius: 12,
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    fontFamily: "NotoSansThai_400Regular",
    color: C.ink,
  },
  card: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 16,
    padding: 16,
    shadowColor: "#48262B",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    gap: 7,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  quickLinks: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 18,
  },
  two: { flexDirection: "row", gap: 10 },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  segment: {
    flexDirection: "row",
    backgroundColor: "#F0E7E3",
    borderRadius: 12,
    padding: 3,
    marginBottom: 18,
  },
  chip: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: C.line,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "#fff",
  },
  chipActive: { borderColor: C.orange, backgroundColor: "#FFF8F4" },
  chipText: {
    fontSize: 10,
    color: "#715E60",
    fontFamily: "NotoSansThai_600SemiBold",
  },
  chipTextActive: { color: C.orange },
  welcomeArt: {
    height: 410,
    borderRadius: 20,
    backgroundColor: "#FFE8D8",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  artText: {
    backgroundColor: "#fff",
    padding: 18,
    borderRadius: 14,
    lineHeight: 25,
    color: C.ink,
    transform: [{ rotate: "-3deg" }],
  },
  scoreArt: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 10,
    borderColor: C.amber,
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 24,
    color: C.wine,
    fontFamily: "NotoSansThai_800ExtraBold",
  },
  dots: { flexDirection: "row", justifyContent: "center", gap: 5 },
  dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.line },
  dotOn: { width: 18, backgroundColor: C.orange },
  authTitleRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    marginBottom: 10,
  },
  miniLogo: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: C.orange,
    alignItems: "center",
    justifyContent: "center",
  },
  strength: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: -10,
    marginBottom: 12,
  },
  strengthOn: { height: 4, flex: 1, backgroundColor: C.orange },
  strengthMid: { height: 4, flex: 1, backgroundColor: C.amber },
  strengthOff: { height: 4, flex: 1, backgroundColor: C.line },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginVertical: 12,
  },
  line: { height: 1, backgroundColor: C.line, flex: 1 },
  bottomLink: {
    textAlign: "center",
    marginTop: "auto",
    paddingTop: 25,
    color: C.orange,
    fontFamily: "NotoSansThai_700Bold",
    fontSize: 12,
  },
  authHero: { alignItems: "center", gap: 10, marginVertical: 45 },
  lock: {
    width: 70,
    height: 70,
    borderRadius: 24,
    backgroundColor: "#FFF0E8",
    alignItems: "center",
    justifyContent: "center",
    color: C.orange,
  },
  upload: {
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#E8B9A5",
    borderRadius: 16,
    minHeight: 240,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  verifySteps: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  photos: { flexDirection: "row", gap: 8, marginTop: 8 },
  photoMain: {
    width: 76,
    height: 76,
    borderRadius: 18,
    backgroundColor: C.orange,
    alignItems: "center",
    justifyContent: "center",
  },
  photoImage: { width: "100%", height: "100%", borderRadius: 16 },
  photoAdd: {
    width: 70,
    height: 76,
    borderRadius: 18,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#E8B9A5",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarLetter: {
    fontSize: 22,
    color: "#fff",
    fontFamily: "NotoSansThai_700Bold",
  },
  slider: {
    height: 7,
    borderRadius: 4,
    backgroundColor: "#EADFDA",
    marginVertical: 12,
  },
  sliderOn: {
    height: 7,
    width: "68%",
    borderRadius: 4,
    backgroundColor: C.orange,
  },
  progressTop: { alignItems: "flex-end" },
  progressCount: { color: C.muted, fontSize: 11 },
  track: {
    height: 5,
    borderRadius: 3,
    backgroundColor: "#EADFDA",
    overflow: "hidden",
  },
  fill: { height: "100%", borderRadius: 3, backgroundColor: C.orange },
  introCenter: {
    flex: 1,
    minHeight: 530,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  heart: {
    width: 72,
    height: 72,
    borderRadius: 22,
    backgroundColor: C.orange,
    color: "#fff",
    fontSize: 40,
    textAlign: "center",
    textAlignVertical: "center",
  },
  cover: { height: 95, backgroundColor: "#DD4425", borderRadius: 14 },
  avatarFloat: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: C.amber,
    alignItems: "center",
    justifyContent: "center",
    marginTop: -34,
    borderWidth: 3,
    borderColor: "#fff",
  },
  nav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 72,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: C.line,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 9,
  },
  navItem: { alignItems: "center", width: 70 },
  navIcon: { fontSize: 21, color: C.muted },
  navText: { fontSize: 9, color: C.muted },
  profileCard: {
    height: 515,
    borderRadius: 22,
    backgroundColor: C.wine,
    padding: 18,
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  verified: {
    position: "absolute",
    top: 18,
    left: 18,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#fff",
    padding: 5,
  },
  score: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#fff",
    borderWidth: 7,
    borderColor: C.amber,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  scoreText: {
    fontSize: 15,
    color: C.wine,
    fontFamily: "NotoSansThai_800ExtraBold",
  },
  ghost: {
    position: "absolute",
    fontSize: 170,
    color: "rgba(255,255,255,.08)",
    alignSelf: "center",
    top: 150,
  },
  profileCopy: { gap: 7 },
  profileName: {
    fontSize: 25,
    color: "#fff",
    fontFamily: "NotoSansThai_800ExtraBold",
  },
  tap: { textAlign: "center", color: C.muted },
  actions: { flexDirection: "row", justifyContent: "center", gap: 18 },
  reject: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  like: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: C.orange,
    alignItems: "center",
    justifyContent: "center",
  },
  filterBackdrop: { height: 140, borderRadius: 18, backgroundColor: "#4A252B" },
  sheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: C.bg,
    paddingTop: 12,
    gap: 13,
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D8C7C1",
    alignSelf: "center",
  },
  personRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: C.wine,
    alignItems: "center",
    justifyContent: "center",
  },
  smallAction: {
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: C.line,
  },
  matchPage: {
    flex: 1,
    backgroundColor: "#78122D",
    padding: 22,
    justifyContent: "center",
    gap: 16,
  },
  matchEyebrow: {
    color: C.amber,
    letterSpacing: 2,
    textAlign: "center",
    fontFamily: "NotoSansThai_700Bold",
  },
  matchTitle: {
    fontSize: 40,
    lineHeight: 48,
    color: "#fff",
    textAlign: "center",
    fontFamily: "NotoSansThai_800ExtraBold",
  },
  matchAvatars: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  matchAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: C.amber,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: C.amber,
  },
  matchScore: {
    width: 45,
    height: 45,
    borderRadius: 23,
    backgroundColor: "#fff",
    borderWidth: 4,
    borderColor: C.amber,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    marginHorizontal: -8,
  },
  matchCopy: {
    color: "#F5D4DA",
    textAlign: "center",
    lineHeight: 21,
    marginVertical: 12,
  },
  notifyIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  online: { textAlign: "center", color: C.green, fontSize: 11, marginTop: -12 },
  chatBody: { flex: 1, backgroundColor: "#F8F2EE", padding: 18, gap: 12 },
  matchDate: { textAlign: "center", color: C.muted, fontSize: 10 },
  bubbleIn: {
    alignSelf: "flex-start",
    maxWidth: "75%",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 13,
  },
  bubbleOut: {
    alignSelf: "flex-end",
    maxWidth: "78%",
    backgroundColor: C.orange,
    borderRadius: 14,
    padding: 13,
  },
  voice: {
    alignSelf: "flex-start",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    color: C.orange,
  },
  composer: {
    height: 74,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    backgroundColor: "#fff",
  },
  send: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: C.orange,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionLabel: {
    color: C.muted,
    fontSize: 10,
    fontFamily: "NotoSansThai_700Bold",
    marginTop: 10,
  },
  settingRow: {
    height: 55,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  adminHero: { minHeight: 420, alignItems: "center", justifyContent: "center" },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  stat: {
    width: "48%",
    height: 100,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 14,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  statNum: { fontSize: 25, fontFamily: "NotoSansThai_800ExtraBold" },
});

