import { Platform, StyleSheet } from "react-native";

export const serifFont = Platform.select({
  ios: "Georgia",
  android: "serif",
  default: "serif",
});

export const introStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FEFCFA",
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FAF6F0",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  backChevron: {
    fontSize: 18,
    color: "#463826",
    fontWeight: "bold",
  },
  stepBadge: {
    backgroundColor: "#FAF6F0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  stepBadgeText: {
    fontFamily: serifFont,
    fontSize: 12,
    fontWeight: "bold",
    color: "#C64338",
  },
  heroBox: {
    backgroundColor: "#FAF6F0",
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  heroIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FFF0BB",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  heroIconText: {
    fontSize: 28,
  },
  heroTitle: {
    fontFamily: serifFont,
    fontSize: 22,
    fontWeight: "bold",
    color: "#463826",
    textAlign: "center",
    marginBottom: 8,
  },
  heroSubText: {
    fontFamily: serifFont,
    fontSize: 14,
    color: "#74675E",
    textAlign: "center",
    lineHeight: 20,
  },
  sectionTitle: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 14,
  },
  categoriesGrid: {
    gap: 12,
    marginBottom: 20,
  },
  catCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  catIconBox: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#FAF6F0",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  catIcon: {
    fontSize: 20,
  },
  catInfo: {
    flex: 1,
  },
  catTitle: {
    fontFamily: serifFont,
    fontSize: 14,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 2,
  },
  catSub: {
    fontFamily: serifFont,
    fontSize: 12,
    color: "#8D7C75",
  },
  infoBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF0BB",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#FFD477",
  },
  infoText: {
    fontFamily: serifFont,
    fontSize: 13,
    fontWeight: "600",
    color: "#7F232D",
    flex: 1,
  },
  startButton: {
    height: 54,
    borderRadius: 14,
    backgroundColor: "#C64338",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#C64338",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  startButtonText: {
    fontFamily: serifFont,
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
});

export const qStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FEFCFA",
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#FAF6F0",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  backChevron: {
    fontSize: 18,
    color: "#463826",
    fontWeight: "bold",
  },
  stepCountBadge: {
    backgroundColor: "#FAF6F0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  stepCountText: {
    fontFamily: serifFont,
    fontSize: 12,
    fontWeight: "bold",
    color: "#C64338",
  },
  progressTrack: {
    height: 6,
    backgroundColor: "#EADCD3",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 20,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#C64338",
    borderRadius: 3,
  },
  title: {
    fontFamily: serifFont,
    fontSize: 22,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 6,
  },
  subText: {
    fontFamily: serifFont,
    fontSize: 14,
    color: "#74675E",
    lineHeight: 20,
    marginBottom: 20,
  },
  groupCard: {
    backgroundColor: "#FAF6F0",
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  groupLabel: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 12,
  },
  optionsContainer: {
    gap: 8,
  },
  optionChip: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1.5,
    borderColor: "#EADCD3",
  },
  optionChipSelected: {
    backgroundColor: "#FFF0BB",
    borderColor: "#FFD477",
  },
  optionText: {
    fontFamily: serifFont,
    fontSize: 14,
    color: "#463826",
    fontWeight: "500",
  },
  optionTextSelected: {
    color: "#7F232D",
    fontWeight: "bold",
  },
  noteCard: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#FFF0BB",
    borderRadius: 14,
    padding: 14,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#FFD477",
  },
  noteText: {
    fontFamily: serifFont,
    fontSize: 13,
    color: "#7F232D",
    lineHeight: 18,
    flex: 1,
  },
  nextButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: "#C64338",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    shadowColor: "#C64338",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  nextButtonText: {
    fontFamily: serifFont,
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
});

export const summaryStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FEFCFA",
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
  },
  heroBox: {
    alignItems: "center",
    marginBottom: 24,
  },
  badgeIconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#FFF0BB",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    borderWidth: 2,
    borderColor: "#FFD477",
  },
  heroIconText: {
    fontSize: 34,
  },
  title: {
    fontFamily: serifFont,
    fontSize: 24,
    fontWeight: "bold",
    color: "#463826",
    textAlign: "center",
    marginBottom: 8,
  },
  subText: {
    fontFamily: serifFont,
    fontSize: 14,
    color: "#74675E",
    textAlign: "center",
    lineHeight: 20,
  },
  sectionTitle: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 12,
  },
  cardPreview: {
    backgroundColor: "#FAF6F0",
    borderRadius: 20,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#EADCD3",
    flexDirection: "row",
    alignItems: "center",
  },
  cardAvatarWrap: {
    marginRight: 14,
  },
  cardAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#F0CDBF",
    alignItems: "center",
    justifyContent: "center",
  },
  cardAvatarText: {
    fontFamily: serifFont,
    fontSize: 16,
    fontWeight: "bold",
    color: "#7F232D",
  },
  cardInfo: {
    flex: 1,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 2,
  },
  cardName: {
    fontFamily: serifFont,
    fontSize: 17,
    fontWeight: "bold",
    color: "#463826",
  },
  verifiedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#E6F4EA",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  verifiedPillText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#137333",
  },
  cardMeta: {
    fontFamily: serifFont,
    fontSize: 12,
    color: "#8D7C75",
    marginBottom: 8,
  },
  signalsRow: {
    flexDirection: "row",
  },
  signalChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFF0BB",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  signalChipText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#7F232D",
  },
  summaryCard: {
    backgroundColor: "#FAF6F0",
    borderRadius: 18,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  summaryTitle: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE8E1",
  },
  summaryLabel: {
    fontFamily: serifFont,
    fontSize: 13,
    color: "#463826",
  },
  summaryValue: {
    fontFamily: serifFont,
    fontSize: 13,
    fontWeight: "bold",
    color: "#137333",
  },
  completeButton: {
    height: 54,
    borderRadius: 14,
    backgroundColor: "#C64338",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#C64338",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  completeButtonText: {
    fontFamily: serifFont,
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
});
