import { Platform, StyleSheet } from "react-native";

/** Thai body font, matching the app-wide default set in App.tsx. */
export const serif = "NotoSansThai_400Regular";

/** Serif used for headings in this feature. */
export const serifFont = Platform.select({
  ios: "Georgia",
  android: "serif",
  default: "serif",
});

export const auth = StyleSheet.create({
  flex: { flex: 1 },
  animatedContent: { flexGrow: 1 },
  safe: { flex: 1, backgroundColor: "#FEFCFA" },
  page: {
    flexGrow: 1,
    paddingHorizontal: 30,
    paddingTop: 68,
    paddingBottom: 28,
  },
  loginPage: { paddingTop: 40 },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 17,
    marginBottom: 33,
  },
  loginTitleRow: { marginLeft: 74, marginBottom: 43 },
  logoTile: {
    width: 58,
    height: 58,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#B83A31",
  },
  houseIcon: { color: "#FFF8DA", fontSize: 28, lineHeight: 31 },
  title: {
    color: "#42362A",
    fontFamily: serif,
    fontSize: 22,
    fontWeight: "700",
  },
  subtitle: {
    color: "#63564D",
    fontFamily: serif,
    fontSize: 15,
    marginTop: 2,
  },
  fieldGroup: { marginBottom: 10 },
  fieldLabel: {
    color: "#6C5F56",
    fontFamily: serif,
    fontWeight: "700",
    fontSize: 13,
    marginBottom: 7,
  },
  field: {
    height: 45,
    borderWidth: 1,
    borderColor: "#E8DFC8",
    borderRadius: 9,
    backgroundColor: "#FFFFFF",
    paddingLeft: 15,
    paddingRight: 7,
    flexDirection: "row",
    alignItems: "center",
  },
  fieldInput: {
    flex: 1,
    color: "#2E241D",
    fontFamily: serif,
    fontSize: 12,
    paddingVertical: 0,
  },
  eye: { color: "#80715F", fontSize: 18, paddingHorizontal: 8 },
  passwordStrength: {
    height: 12,
    marginTop: -4,
    marginBottom: 5,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  strengthBar: { height: 4, flex: 1, borderRadius: 3 },
  strengthLabel: {
    width: 54,
    color: "#378B3B",
    fontFamily: serif,
    fontSize: 11,
    textAlign: "right",
  },
  strengthHint: {
    color: "#6C5F56",
    fontFamily: serif,
    fontSize: 10.5,
    lineHeight: 15,
    marginBottom: 12,
  },
  termsRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 1,
    marginBottom: 18,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#D9CDBF",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: { backgroundColor: "#CC402E", borderColor: "#CC402E" },
  checkmark: { color: "#FFFFFF", fontSize: 12, fontWeight: "700" },
  termsText: {
    flex: 1,
    color: "#9B8C81",
    fontFamily: serif,
    fontSize: 11,
    lineHeight: 19,
  },
  termsLink: { color: "#C72F2F", textDecorationLine: "underline" },
  primaryButton: {
    height: 51,
    borderRadius: 8,
    backgroundColor: "#BF3D3C",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5,
  },
  primaryButtonPressed: { opacity: 0.72 },
  primaryButtonDisabled: { opacity: 0.58 },
  primaryButtonText: {
    color: "#FFF9F0",
    fontFamily: serif,
    fontSize: 15,
    fontWeight: "700",
  },
  error: {
    color: "#B42336",
    fontFamily: serif,
    fontSize: 12,
    marginBottom: 10,
  },
  footerLink: {
    marginTop: "auto",
    paddingTop: 50,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  footerMuted: { color: "#77685E", fontFamily: serif, fontSize: 11 },
  footerAccent: {
    color: "#C62828",
    fontFamily: "NotoSansThai_700Bold",
    fontSize: 11,
    textDecorationLine: "underline",
  },
  loginOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 1,
    marginBottom: 39,
    paddingHorizontal: 4,
  },
  checkRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  optionText: { color: "#685A50", fontFamily: serif, fontSize: 11 },
  forgotLink: {
    color: "#D00000",
    fontFamily: serif,
    fontWeight: "700",
    fontSize: 11,
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    marginTop: 41,
    marginBottom: 39,
  },
  dividerLine: { height: 1, flex: 1, backgroundColor: "#BFB9B4" },
  dividerText: { color: "#74675E", fontFamily: serif, fontSize: 11 },
  socialRow: { flexDirection: "row", gap: 14 },
  socialButton: {
    flex: 1,
    height: 42,
    borderWidth: 1,
    borderColor: "#E7DDC7",
    borderRadius: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  socialButtonPressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  socialButtonDisabled: { opacity: 0.55 },
  googleIcon: {
    color: "#766F66",
    fontSize: 20,
    fontWeight: "700",
  },
  socialText: {
    color: "#4F443C",
    fontFamily: serif,
    fontSize: 15,
    fontWeight: "700",
  },
  forgotPage: {
    flexGrow: 1,
    paddingHorizontal: 30,
    paddingTop: 78,
    paddingBottom: 28,
  },
  forgotHeader: { flexDirection: "row", alignItems: "center", gap: 13 },
  backButton: {
    width: 36,
    height: 36,
    borderWidth: 1,
    borderColor: "#E3DAC6",
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  backIcon: { color: "#776C61", fontSize: 29, lineHeight: 30 },
  forgotHeaderTitle: {
    color: "#40352A",
    fontFamily: serif,
    fontSize: 18,
    fontWeight: "700",
  },
  resetHero: { alignItems: "center", marginTop: 82, marginBottom: 25 },
  lockTile: {
    width: 60,
    height: 60,
    borderRadius: 14,
    backgroundColor: "#F6CBC5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  lockShackle: {
    width: 15,
    height: 14,
    borderWidth: 2,
    borderColor: "#D84634",
    borderBottomWidth: 0,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    marginBottom: -2,
  },
  lockBody: {
    width: 23,
    height: 19,
    borderWidth: 2,
    borderColor: "#D84634",
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  lockKeyhole: {
    width: 3,
    height: 6,
    borderRadius: 2,
    backgroundColor: "#D84634",
  },
  resetTitle: {
    color: "#493C30",
    fontFamily: serif,
    fontSize: 18,
    fontWeight: "700",
  },
  resetDescription: {
    color: "#61554C",
    fontFamily: serif,
    fontSize: 11,
    lineHeight: 19,
    textAlign: "center",
    marginTop: 7,
  },
  inlineButton: {
    minWidth: 64,
    height: 31,
    paddingHorizontal: 8,
    borderRadius: 5,
    backgroundColor: "#477AAF",
    alignItems: "center",
    justifyContent: "center",
  },
  inlineButtonText: {
    color: "#FFFFFF",
    fontFamily: serif,
    fontSize: 8,
    fontWeight: "700",
    textAlign: "center",
  },
  resendCard: {
    height: 53,
    borderWidth: 1,
    borderColor: "#E9DFC7",
    borderRadius: 14,
    backgroundColor: "#FFFDF4",
    marginHorizontal: 3,
    marginTop: 15,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 25,
    gap: 14,
  },
  mailIcon: { color: "#F08B7B", fontSize: 21 },
  resendText: {
    flex: 1,
    color: "#8E4B49",
    fontFamily: serif,
    fontSize: 11,
  },
});
