import { Platform, StyleSheet } from "react-native";

export const serifFont = Platform.select({
  ios: "Georgia",
  android: "serif",
  default: "serif",
});

/**
 * The page chrome (safe area, top bar, empty state, primary button) shared by
 * every screen in this feature — feed, filters, matches, the match celebration
 * and likes all sit on it.
 */
export const feedStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FEFCFA",
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  appTitle: {
    fontFamily: serifFont,
    fontSize: 24,
    fontWeight: "bold",
    color: "#463826",
  },
  filterBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FAF6F0",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EADCD3",
    gap: 6,
  },
  filterBtnText: {
    fontFamily: serifFont,
    fontSize: 13,
    fontWeight: "600",
    color: "#463826",
  },
  quickRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  quickPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FAF6F0",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EADCD3",
    gap: 6,
  },
  quickPillText: {
    fontFamily: serifFont,
    fontSize: 13,
    fontWeight: "600",
    color: "#463826",
  },
  cardContainer: {
    flex: 1,
    borderRadius: 24,
    backgroundColor: "#FAF6F0",
    borderWidth: 1,
    borderColor: "#EADCD3",
    overflow: "hidden",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  cardImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
  },
  cardAvatarFallback: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F0CDBF",
    alignItems: "center",
    justifyContent: "center",
  },
  cardAvatarLetter: {
    fontFamily: serifFont,
    fontSize: 72,
    fontWeight: "bold",
    color: "#7F232D",
  },
  verifiedBadge: {
    position: "absolute",
    top: 16,
    left: 16,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  verifiedText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  scoreBadge: {
    position: "absolute",
    top: 16,
    right: 16,
    backgroundColor: "#FFF0BB",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FFD477",
  },
  scoreText: {
    fontFamily: serifFont,
    fontSize: 13,
    fontWeight: "bold",
    color: "#7F232D",
  },
  cardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    backgroundColor: "rgba(30, 20, 15, 0.78)",
  },
  cardName: {
    fontFamily: serifFont,
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  cardDetails: {
    fontFamily: serifFont,
    fontSize: 13,
    color: "#EADCD3",
    marginBottom: 10,
  },
  chipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 8,
  },
  cardChip: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  cardChipText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  tapHint: {
    fontFamily: serifFont,
    fontSize: 11,
    color: "#D6C6B8",
    textAlign: "center",
    marginTop: 4,
  },
  actionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    paddingVertical: 16,
  },
  btnPass: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#EADCD3",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  btnSuper: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFF0BB",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#FFD477",
  },
  btnLike: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#C64338",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#C64338",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  emptyBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backgroundColor: "#FAF6F0",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EADCD3",
    marginBottom: 20,
  },
  emptyTitle: {
    fontFamily: serifFont,
    fontSize: 20,
    fontWeight: "bold",
    color: "#463826",
    textAlign: "center",
    marginBottom: 8,
  },
  emptySub: {
    fontFamily: serifFont,
    fontSize: 14,
    color: "#74675E",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  refreshBtn: {
    height: 48,
    borderRadius: 12,
    backgroundColor: "#C64338",
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  refreshBtnText: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
});

export const filterStyles = StyleSheet.create({
  sectionCard: {
    backgroundColor: "#FAF6F0",
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  sectionTitle: {
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: "bold",
    color: "#463826",
  },
  pillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pill: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  pillActive: {
    backgroundColor: "#FFF0BB",
    borderColor: "#FFD477",
  },
  pillText: {
    fontFamily: serifFont,
    fontSize: 13,
    fontWeight: "600",
    color: "#463826",
  },
  pillTextActive: {
    color: "#7F232D",
    fontWeight: "bold",
  },
  scoreRow: {
    alignItems: "center",
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EADCD3",
  },
  scoreValueText: {
    fontFamily: serifFont,
    fontSize: 18,
    fontWeight: "bold",
    color: "#C64338",
  },
});

export const matchStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#FEFCFA",
  },
  container: {
    flex: 1,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  eyebrow: {
    fontFamily: serifFont,
    fontSize: 16,
    fontWeight: "bold",
    color: "#C64338",
  },
  title: {
    fontFamily: serifFont,
    fontSize: 32,
    fontWeight: "bold",
    color: "#463826",
    marginBottom: 24,
  },
  avatarsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#F0CDBF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#EADCD3",
  },
  avatarText: {
    fontFamily: serifFont,
    fontSize: 18,
    fontWeight: "bold",
    color: "#7F232D",
  },
  scoreChip: {
    backgroundColor: "#C64338",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginHorizontal: -12,
    zIndex: 10,
  },
  scoreChipText: {
    fontFamily: serifFont,
    fontSize: 12,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  copyText: {
    fontFamily: serifFont,
    fontSize: 15,
    color: "#74675E",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 32,
  },
  secondaryBtn: {
    marginTop: 14,
    paddingVertical: 12,
  },
  secondaryBtnText: {
    fontFamily: serifFont,
    fontSize: 14,
    fontWeight: "bold",
    color: "#7F232D",
  },
});
